import os
import argparse
from datetime import datetime
import json
from pathlib import Path

def create_feedback_artifact(direction, artifact_type, reason, content, escalation, requires_adr):
    feedback_dir = Path(".cursor/feedback")
    feedback_dir.mkdir(parents=True, exist_ok=True)
    
    timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
    filename = f"{timestamp}_{direction}_{artifact_type}.md"
    filepath = feedback_dir / filename
    
    escalation_badge = "🔴 ESCALATED" if escalation.lower() == 'true' else "🟢 Standard"
    adr_badge = "📝 REQUIRES ADR" if requires_adr.lower() == 'true' else ""
    
    markdown_content = f"""# Feedback Artifact: {direction.replace('_', ' ').title()}

**Date:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
**Type:** {artifact_type}
**Status:** {escalation_badge} {adr_badge}

## Trigger Reason
{reason}

## Content / Action Required
{content}

---
*Generated by org-feedback-loop skill*
"""
    
    with open(filepath, "w") as f:
        f.write(markdown_content)
        
    print(f"✅ Feedback artifact generated successfully at: {filepath}")
    
    # Optionally print json representation for tooling
    data = {
        "direction": direction,
        "type": artifact_type,
        "reason": reason,
        "content": content,
        "requires_escalation": escalation.lower() == 'true',
        "requires_adr": requires_adr.lower() == 'true',
        "file": str(filepath)
    }
    print("\nMetadata:")
    print(json.dumps(data, indent=2))

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Create a Feedback Loop Artifact")
    parser.add_argument("--direction", required=True, help="Direction of feedback (e.g., qa_to_documentation)")
    parser.add_argument("--type", required=True, help="Type of artifact (e.g., documentation_gap)")
    parser.add_argument("--reason", required=True, help="Reason this feedback was triggered")
    parser.add_argument("--content", required=True, help="Content or action required")
    parser.add_argument("--requires-escalation", default="false", help="True if requires escalation")
    parser.add_argument("--requires-adr", default="false", help="True if requires a Decision Record")
    
    args = parser.parse_args()
    
    create_feedback_artifact(
        args.direction,
        args.type,
        args.reason,
        args.content,
        args.requires_escalation,
        args.requires_adr
    )